### PR TITLE
Conan server thoubleshooting

### PR DESCRIPTION
**Pull request by uilianries**
Explain how to fix multiple workers and Conan server migration.

related issue: https://github.com/conan-io/conan/issues/4723

### CODE REVIEW

**Comment by uilianries** [comment]
some links are broken again. thanks Microsoft!

**Comment by danimtb** [comment]
Will fix the broken links, thanks!

**Comment by uilianries** [comment]
Thanks @danimtb :clap:

**Comment by danimtb** [comment]
Please update this PR with latest changes from develop branch

**Comment by uilianries** [comment]
I've forced the commit to revert my last merge from docs:develop branch.

**Comment by danimtb** [comment]
ok. This PR goes to master, then. Good to go

**Pull request merged**
