### PR TITLE
Minor English tweaks.

### PR DESCRIPTION
**Pull request by tamboril**
I hope this is useful.  I would like to help out with the readability of the docs from time to time.

### CODE REVIEW

**Comment by memsharded** [comment]
This is really appreciated, docs are hard to write, so taking the time to review and improve is fantastic. Thank you very much!

**Comment by tamboril** [comment]
Oh good. Now that I know that, I will pick through some more pages and submit P.R.'s for review.

John

**Comment by tamboril** [comment]
Would you prefer these kinds of changes branch from `develop` or `master` ?

**Comment by memsharded** [comment]
To master, please. Develop is to document on-going development that has not been released yet. Anything that applies to current release, go to master, so it is automatically published to docs.conan.io. Thanks!

**Pull request merged**
