### PR TITLE
Fix a bunch of typos

### PR DESCRIPTION
**Pull request by liberforce**
Please use `make spelling` once in a while!

### CODE REVIEW

**Comment by liberforce** [comment]
Ending my job where I use conan to switch on something else, so I guess someone else will need to pick up the responsability or fixing the typos with `make spelling` :smile:

**Comment by danimtb** [comment]
Thanks @liberforce!

We'll try to use the spellchecker but if you happen to have the time come around once in a while and take a look 😄 

Good luck in your new job and thanks again 👍

**Comment by liberforce** [comment]
Thanks to you, and the team. Even if I sometimes sounded like the stuff was not working the way I liked, that's because I value homogeneity and a good user experience and wanted a better user experience for the users that would come after me. I found the team super open, welcoming, listening to feedback, and very reactive to integrate changes. This deserves a :+1: . Keep up the good work!

**Comment by jgsogo** [comment]
Thanks! Good luck in your new job... and let your new colleagues know about Conan 😄

**Comment by memsharded** [comment]
Thanks to you for so many contributions and your efforts to improve Conan. Really appreciated!
Best luck!

**Comment by lasote** [comment]
Good luck and thanks for everything!!

**Pull request merged**
