### PR TITLE
#968 Move how to extract license

### LINKED ISSUE #968: How to extract license from headers
I was looking for "how to extract the license from a header file".

It supposed to be in [howtos](https://docs.conan.io/en/latest/howtos.html) page, but I found in [conan center guide](https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html?highlight=extract)

Additionally, there is [collect licenses](https://docs.conan.io/en/latest/howtos/collect_licenses.html) in howtos.

Could we move or refer that trick in howtos?

### PR DESCRIPTION
**Pull request by uilianries**
Hi!

This PR is related to #968 

I moved the section the explain how to extract a license from a header file to "Howtos" tree.

closes #968

### CODE REVIEW

**Comment by uilianries** [comment]
It could not download from SVN page.

https://travis-ci.org/conan-io/docs/builds/466965352#L1554

```
(line 1045) broken    http://svnbook.red-bean.com/en/1.7/svn.advanced.pegrevs.html - HTTPConnectionPool(host='svnbook.red-bean.com', port=80): Max retries exceeded with url: /en/1.7/svn.advanced.pegrevs.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2af4546cc908>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by danimtb** [comment]
Yes, I will take a look in a moment before merging this

**Comment by danimtb** [comment]
Will merge this after #971

**Comment by uilianries** [comment]
nice!

**Pull request merged**
