### PR TITLE
Fix redirect and broken links

### PR DESCRIPTION
**Pull request by danimtb**
Will push the changes later to develop branch

### CODE REVIEW

**Comment by uilianries** [comment]
> (line   34) broken    https://docs.microsoft.com/en-us/cpp/ide/working-with-project-properties?view=vs-2017 - 404 Client Error: Not Found for url: https://docs.microsoft.com/en-us/cpp/ide/cpp/build/working-with-project-properties?view=vs-2017

**Comment by uilianries** [comment]
The link has been updated to `https://docs.microsoft.com/en-us/cpp/ide/walkthrough-working-with-projects-and-solutions-cpp?view=vs-2017`

**Comment by danimtb** [comment]
I have compared it with the chached broken link and I think it is more similar to the one I used. Thanks anyway!

**Comment by danimtb** [comment]
fixed CI

**Pull request merged**
