### PR TITLE
Enable announcement banner for "cooking with Conan" event

### PR DESCRIPTION
**Pull request by prince-chrismc**
Been a while since I've seen one, let me know if this is too much or just right (or too short).

image

### CODE REVIEW

**Review by memsharded — APPROVED** [review]
Can be merged, you need to do the PR to master branch instead to be published.

**Comment by prince-chrismc** [comment]
develop vs master is a messy slope 🙈

**Comment by uilianries** [comment]
@prince-chrismc You can set to master branch. Need to click on edit button for the title, then the target branch will show up as a list box.

**Comment by prince-chrismc** [comment]
There's other commits that need to be removed

**Comment by memsharded** [comment]
Need to branch from master, cherry-pick or similar.

The problem is that this might release docs for unreleased Conan 1.X future version.

**Comment by prince-chrismc** [comment]
Should look much better

**Review by czoido — APPROVED** [review]

**Pull request merged**
