### PR TITLE
Remake the 2.0 logo 

### PR DESCRIPTION
**Pull request by prince-chrismc**
Before vs After

image

### CODE REVIEW

**Review by memsharded — APPROVED** [review]
looks good, but recall if you want it live now, the branch should be ``release/2.0``

**Comment by RubenRBS** [comment]
Yay! Thanks for fixing my mess :)

**Comment by prince-chrismc** [comment]
> looks good, but recall if you want it live now, the branch should be `release/2.0`

I did not know this changed but thanks for the heads up.

I will need to wait for the next release since there are too many changes in my branch -- but I make my fork better next time :)

**Comment by czoido** [comment]
> > looks good, but recall if you want it live now, the branch should be `release/2.0`
> 
> I did not know this changed but thanks for the heads up.
> 
> I will need to wait for the next release since there are too many changes in my branch -- but I make my fork better next time :)

This looks much better! I think this is worth taking live, let me cherry-pick the changes and open a new PR to release/2.0

**Comment by czoido** [comment]
Closed in favor of https://github.com/conan-io/docs/pull/3082

**Pull request closed without merging**
