### PR TITLE
Add ios-cmake toolchain docs

### PR DESCRIPTION
**Pull request by a4z**

### CODE REVIEW

**Comment by lasote** [comment]
Thanks for this. I think first we need to try supporting all this into the new `CMakeToolchain` to have native support in Conan.

**Comment by a4z** [comment]
Not sure what you mean,  ios-cmake is independent, you can use it basically stand alone, with out anything else, and it will just work

**Comment by lasote** [comment]
Then probably shouldn't be documented in the conan docs. Or not like this, I meant we should explore a better integration with the toolchain than using a package with a build require. That's all.

**Comment by a4z** [comment]
Then explain why the so called conan-darwin-toolchain is mentioned. 
It was a point of confusion for many people over the last years. They got through the conan docs to that package, instead to the ios-cmake toolchain,
I fix that here. The way to build for iOS tvOS watchOS is ios-cmake, that is proven to work for many people since years.

**Comment by lasote** [comment]
Because the project evolves. Nowadays I won't add `conan-darwin-toolchain` either.

**Pull request closed without merging**
