### PR TITLE
Update logging level names

### PR DESCRIPTION
**Pull request by uilianries**
Related PR: https://github.com/conan-io/conan/pull/5772

### CODE REVIEW

**Comment by Minimonium** [comment]
It'd be cool to have some examples of what we can expect to get from these log levels.

**Comment by jgsogo** [comment]
Yes, @Minimonium , it would be nice, but I think that the two files modified in this PR (up to now) aren't the place to add this information... those are sections inside already long files.

I would suggest improving the `Logging` one (https://docs.conan.io/en/latest/mastering/logging.html): there we talk about `CONAN_TRACE_FILE` but we say nothing about the logging level and it would probably make a lot of sense, wdyt @danimtb ?

**Comment by danimtb** [comment]
Yes, makes sense to have that in the logging one

**Comment by uilianries** [comment]
> Yes, @Minimonium , it would be nice, but I think that the two files modified in this PR (up to now) aren't the place to add this information... those are sections inside already long files.

I gonna open a new issue to introduce those examples.

**Pull request merged**
