### PR TITLE
Update Bincrafters remote

### PR DESCRIPTION
**Pull request by Croydon**

### CODE REVIEW

**Review by uilianries — APPROVED** [review]

**Review by memsharded — APPROVED** [review]

**Comment by uilianries** [comment]
@Croydon Thank you for this contribution. Do you think this PR can be converted to "Read for Review"?

**Review by SSE4 — APPROVED** [review]

**Comment by Croydon** [comment]
> @Croydon Thank you for this contribution. Do you think this PR can be converted to "Read for Review"?

Not yet. I would like to wait at least a few more days in the hope that we have more answers about our Artifactory status until then 🙂

**Comment by memsharded** [comment]
@solvingj will update about status/migration asap

**Comment by memsharded** [comment]
Bintray references were already updated some time ago, this is outdated

**Pull request closed without merging**
