### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by jzinn**

### CODE REVIEW

**Comment by jzinn** [comment]
Your CLA requires access to my email address?  Why?

**Review by memsharded — APPROVED** [review]
Thanks very much for all these fixes!

**Comment by memsharded** [comment]
The docs will be published together with next release. If you want to fix things in prod, need to do the PR to master branch.

**Comment by uilianries** [comment]
> Your CLA requires access to my email address? Why?

@jzinn It uses your email to check if it's the same from commits. In more emails are listed in a PR, all emails should sign the CLA too.

**Pull request merged**
