### PR TITLE
Update Getting started with new package versions (Poco)

### PR DESCRIPTION
**Pull request by uilianries**
Use new package references (without namespace) on getting started to follow the structure than in PR https://github.com/conan-io/examples/pull/38

related comment: https://github.com/conan-io/examples/pull/38#issuecomment-564584878

### CODE REVIEW

**Comment by danimtb** [comment]
Let's have this PR updated with the changes agreed in https://github.com/conan-io/examples/pull/38#issuecomment-566054736 or just close this one and open a new PR @uilianries

**Comment by uilianries** [comment]
@danimtb As result, the current version now is Poco/1.9.4@pocoproject/stable

**Comment by danimtb** [comment]
@uilianries what about the deployment example?? We should update the docs with the changes we are doing at https://github.com/conan-io/examples/pull/38

**Comment by uilianries** [comment]
Good idea @danimtb I think valid applying it for deployment examples too.

**Comment by uilianries** [comment]
@danimtb Both this PR and https://github.com/conan-io/examples/pull/38 are using `Poco/1.9.4@pocoproject/stable` only. The new package `poco/1.9.4@` from CCI is has been excluded from examples repo and docs getting started.

**Pull request merged**
