### PR TITLE
#1564 Sorted Tools reference

### PR DESCRIPTION
**Pull request by uilianries**
Related issue: #1564 

I've made a [small script](https://gist.github.com/uilianries/5737f5c76b31b30bc624defe365b1039) which is able to sort the method block for tools reference. Unfortunately, I didn't find any plugin which is able to do it for readthedocs.

Good luck reviewing the entire reference/tools.rst  :sweat_smile: 

Also, I found some broken references there in tools reference. The build command didn't report because those links are not being used.

NOTE: I want to update other parts of the documentation, but it can result in conflicts due other PRs, so I'll do it by parts.

### CODE REVIEW

**Comment by danimtb** [comment]
We have the glossary section sorted this way https://github.com/conan-io/docs/blob/develop/glossary.rst but I think the `:sorted:` thing only works under a parent section

**Comment by uilianries** [comment]
Oh boy! This is much better! I'll use it instead. Thanks a lot!

**Comment by danimtb** [comment]
let me know if that works, I am not sure but it worths a try

**Comment by uilianries** [comment]
Actually not, reading the [glossary](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-glossary) section on Sphinx, only there the directive **:sorted:** works. I spent some time trying to find a similar way, but the closest approach was using the python config script to sort all indexes. Also, I opened a question on [stackoverflow](https://stackoverflow.com/questions/60320880/how-to-sort-items-on-sphinx-rst), let's see.

**Comment by uilianries** [comment]
According the answer there in StackOverflow, there is no tool for sorting. Thus, I can say this an impossible mission. I'm closing this issue.

**Pull request closed without merging**
