### PR TITLE
Add CONAN_CMAKE_TOOLCHAIN_FILE env var to cmake docs

### PR DESCRIPTION
**Pull request by anton-matosov**

### CODE REVIEW

**Comment by memsharded** [comment]
I am a bit confused, I think that this variable is still not implemented. It is an open issue and pending for next 0.26 release: https://github.com/conan-io/conan/issues/1447

Am I missing something?

**Comment by memsharded** [comment]
Merged, thanks!

**Comment by anton-matosov** [comment]
You are welcome.

P.S.
Sorry about base branch. I was using PR defaults and didn't know about these rules. I will select proper branch next time.

**Comment by memsharded** [comment]
No worries, it is totally fine. The default is master, because most contributions are over the current docs, very few people document features of the next release (develop). So totally appreciated your effort.

**Pull request merged**
