### PR TITLE
Update qmake.rst

### PR DESCRIPTION
**Pull request by Twoflower2**

### CODE REVIEW

**Comment by Twoflower2** [comment]
ta

**Comment by danimtb** [comment]
Sorry @Twoflower2, I forgot to merge your PR after the approval.
Would it be fine to reopen?

Sorry for the delay 😞

**Comment by Twoflower2** [comment]
ok

**Comment by danimtb** [comment]
Thanks a lot! Now the fix is merged and live: https://docs.conan.io/en/latest/reference/generators/qmake.html 😄

**Pull request merged**
