### PR TITLE
change all generator names/refs to lowercase

### PR DESCRIPTION
**Pull request by solvingj**
There was one actual error on this doc which has been corrected (the class had uppercase characters but the instructions with the reference was all lowercase. Made class name lowercase to match recommended convention.  Also, updated several other items in the document to be lowercase and/or add cosmetic improvements.

### CODE REVIEW

**Review by memsharded — APPROVED** [review]

**Review by danimtb — APPROVED** [review]

**Comment by danimtb** [comment]
@solvingj shouldn't this PR target master branch so the change modifies the current documentation?

**Comment by solvingj** [comment]
I never know which one is best for this kind of thing.  It seemed less likely to conflict with and break someone else's active PR if I submit to develop. Also, I looked at the most recent PR and it was pointed to develop so I pointed mine to develop. I can easily change to master if you say so.

**Comment by danimtb** [comment]
As a general rule we try to target develop if it is tied to the next Conan release, otherwise, if it is a fix or improvement to the current docs, it can go live directly and PR should point to master

**Comment by solvingj** [comment]
ok, i'll remember that for next time. i based this one off develop, should i rebase off master then?

**Comment by danimtb** [comment]
np, we merge to develop for now. Thx!

**Pull request merged**
