### PR TITLE
Fix escapement issues on Windows paths

### LINKED ISSUE #788: Escaping issues with windows paths
Some paths using backslashes fail to be interpreted the right way.
Here are the current occurences: 

```
$ git grep 'C:\\\\'
integrations/cmake/find_packages.rst:Sometimes the "official" CMake FindXXX.cmake scripts are not ready to find our libraries (not supported library names for specific settings, fixed installation directories like
reference/config_files/conan.conf.rst:If not specified, the packages marked as `short_paths` will be stored in the `C:\\.conan` (or the current drive letter).
reference/env_vars.rst:marked as `short_paths` will be stored in the `C:\\.conan` (or the current drive letter).
```
So for example, `C:\\.conan` is displayed as `C:.conan`. This is a bit strange because of doubling the [backslashes is how it seems it should work](http://docutils.sourceforge.net/docs/user/rst/quickref.html#escaping).

### PR DESCRIPTION
**Pull request by liberforce**
Fixes #788.

### CODE REVIEW

**Comment by liberforce** [comment]
Hey, could you please give a quick look at that one please?
Thanks

**Comment by danimtb** [comment]
Sorry for the delay @liberforce and thanks for the PR!

**Comment by liberforce** [comment]
@danimtb Could you please confirm this is really fixed? I remember having generated the html locally and checked it but I can't see the change on https://docs.conan.io/en/latest/reference/env_vars.html#conan-user-home . Does it take sometime to be updated?

**Comment by liberforce** [comment]
Oh, right, it just appeared now, so there must be some minutes of delay. Thanks for merging this :)

**Comment by danimtb** [comment]
Yes, docs are generated in Travis CI so it takes few minutes but there is some delay 👍

**Pull request merged**
