### PR TITLE
Line from config.rst missing in official docs.

### PR DESCRIPTION
**Pull request by pepe82sh**
`code-block` directive without a language specification doesn't seem to work properly in sphinx. [The official documentation](https://docs.conan.io/en/latest/reference/commands/consumer/config.html) is missing that line completely. I couldn't find a version in the repo that has that error, so I assume it's not generated correctly.

### CODE REVIEW

**Comment by pepe82sh** [comment]
Whatever I did, it doesn't seem right. Sorry for spamming. How about I create a new PR?

**Comment by danimtb** [comment]
Hi @pepe82sh yes, it would be better to start with a new PR directly to master branch. Thanks a lot and dont worry! 😄

**Comment by memsharded** [comment]
Hi @pepe82sh 

Don't worry. Just close this PR.
Then in your repo, make sure to create the branch from your updated master branch (updated from the main conan-io repo). Don't hesitate to ask if you need help with that.

**Comment by pepe82sh** [comment]
Thanks for offering help! I think it's a basic problem that I work with Github online only. Stuck with SVN at work *sigh*. I'll start over as suggested by @danimtb :)

**Pull request closed without merging**
