### PR TITLE
Update revisions.rst

### PR DESCRIPTION
**Pull request by dslotter**
Fix capitalization. Fix tense of "requests". Fix awkward sentence. Modify phrasing. Add missing comma. Fix tense of "belong". Fix run-on sentence.

### CODE REVIEW

**Comment by dslotter** [comment]
NOTE: The following sentence (at the end of the document) is non-sensical and needs to be totally re-written:

--

If you generate and upload N binary packages for a recipe revision, if you upload the revision you need to generate and upload again the N binaries if you want them to be used with the new recipe.

--

I did not change that sentence because I could not figure out what was originally meant. Please review and re-write that sentence in another revision to the documentation file.

**Comment by memsharded** [comment]
Let me try, it would be something like:

If you generate and upload N binary packages for a recipe with a given revision, if you modify the recipe, and thus the recipe revision, you need to build and upload N new binaries matching that new recipe revision.

Does this make sense?

**Comment by dslotter** [comment]
How about adding the word "then" to improve readability?

If you generate and upload N binary packages for a recipe with a given revision, then if you modify the recipe, and thus the recipe revision, you need to build and upload N new binaries matching that new recipe revision.

**Comment by memsharded** [comment]
Yes, with "then" sounds better, thanks.

**Pull request merged**
