### PR TITLE
sitemap improvements

### PR DESCRIPTION
**Pull request by SSE4**
closes: #1691

- add canonical link (e.g. `<link rel="canonical" href="https://docs.conan.io/en/latest/faq.html"/>`)
- fix sitemap URL generation, removed old code from https://github.com/conan-io/docs/commit/2ce7032f500e1b20c69b9f76426269dcebb14f74, **sphinx-sitemap** is smart enough to generate things on its own
- generated sitemaps for previous versions
- generated sitemapindex

### CODE REVIEW

**Comment by SSE4** [comment]
NOTE: I don't see branches for versions before 1.3, so don't know how to build sitemaps for them

**Comment by jgsogo** [comment]
I have no idea how this *sitemap* thing works. I can see this warning in the CI:

```
sphinx-sitemap warning: No pages generated for sitemap-1.30.xml
```

is it expected?

**Comment by memsharded** [comment]
I have been talking to SEO specialist.  It seems that we understood it wrong, and need to fix. Will check exactly what needs to be done and update here.

**Comment by SSE4** [comment]
@jgsogo no idea, locally it generates valid sitemap for me.

**Comment by SSE4** [comment]
@memsharded it would be nice to understand what exactly is wrong, and what exactly needs to be fixed...

**Comment by AbrilRBS** [comment]
Most of this was fixed as part of the port to newer sphinxversions and with the work of the Conan 2 documentation about a year ago, closing as not-needed anymore :) Thanks!

**Pull request closed without merging**
